### ISSUE TITLE
Certificate problems behind corperate firewall

### ISSUE THREAD

**Issue by Blue1791** [wchatx/direct-access-py#24]
I am behind a corporate firewall. Anytime a production uses certificate validate it fails and I have to disable the verification. I have been unable to figure out where I would add the verify=False to the __init__.py module. I've tried adding it in several location. Any assistance would be appreciated.

**Comment by wchatx** [comment]
Thanks for the message, @Blue1791. You're right, I've worked with several clients with stringent corporate firewalls so this functionality is valuable.

I just deployed version 1.2.1, which allows passing the requests keyword arguments `verify` and `proxies` into the DirectAccessV1 and DirectAccessV2 classes.

Example:
```
    d2 = DirectAccessV2(
        api_key=DIRECTACCESS_API_KEY,
        client_id=DIRECTACCESS_CLIENT_ID,
        client_secret=DIRECTACCESS_CLIENT_SECRET,
        retries=5,
        backoff_factor=1,
        verify=False
    )
```

Upgrade your `direct-access-py` module with `pip install --upgrade directaccess` to take advantage of this. Please report back with any problems...I'll close this issue in a few weeks otherwise.

**Comment by Blue1791** [comment]
They just updated my pc to windows 10 and I do not have th ability to do this yet. I will report on it when I am able to.


Sent from Yahoo Mail for iPad


On Tuesday, July 9, 2019, 7:50 AM, Cole Howard <notifications@github.com> wrote:


Thanks for the message, @Blue1791. You're right, I've worked with several clients with stringent corporate firewalls so this functionality is valuable.

I just deployed version 1.2.1, which allows passing the requests keyword arguments verify and proxies into the DirectAccessV1 and DirectAccessV2 classes.

Example:
    d2 = DirectAccessV2(
        api_key=DIRECTACCESS_API_KEY,
        client_id=DIRECTACCESS_CLIENT_ID,
        client_secret=DIRECTACCESS_CLIENT_SECRET,
        retries=5,
        backoff_factor=1,
        verify=False
    )

Upgrade your direct-access-py module with pip install --upgrade directaccess to take advantage of this. Please report back with any problems...I'll close this issue in a few weeks otherwise.

**Comment by wchatx** [comment]
Closing this issue. Feel free to reopen if there's any problems implementing this.
